### PR TITLE
implement exit and shutdown

### PR DESCRIPTION
**Pull request by Ekopalypse**
Second try :-)

### CODE REVIEW

**Comment by Ekopalypse** [comment]
Need to add the new formatting.

**Comment by danieldaeschle** [comment]
still conflict :D

**Comment by danieldaeschle** [comment]
can you fix that failing CI?

**Comment by Ekopalypse** [comment]
> still conflict :D

hahaha - guess why, and because there is already another PR in the pipeline that modifies the vls.v in the same area, the next version would lead to conflicts again. :-D

> can you fix that failing CI?

I don't own a Mac and to be honest I'm surprised it fails here but passes on Windows and Linux as no changes were made in the tests. Not sure I can be of any help there.

**Comment by danieldaeschle** [comment]
Any change of you caused it. Try to push your changes step by step.

**Comment by danieldaeschle** [comment]
@spytheman what could that cause be?

**Comment by Ekopalypse** [comment]
> Any change of you caused it. Try to push your changes step by step.

OK, I can certainly do that, but is there any way to have the CI run the tests in verbose mode to get more detailed information about which tests are failing?

**Comment by Ekopalypse** [comment]
I'm going to recreate it with several changes, each of which will be transferred individually.

**Pull request closed without merging**
