### PR TITLE
vls: add build command on windows

### PR DESCRIPTION
**Pull request by yuyi98**
This PR add build command on windows.

- Add `build.bat` for windows.
- Will add `build.sh` for linux/mac.

```vlang
PS D:\vls> ./build
Building vls...
> VLS built successfully!
```

### CODE REVIEW

**Comment by JalonSolov** [comment]
Why not just `build.vsh`?

**Comment by medvednikov** [comment]
Yeah with V installed, we shouldn't use bat.

**Comment by yuyi98** [comment]
OK, `build.vsh` is better.

**Comment by nedpals** [comment]
@yuyi98 If possible, can you also integrate it into the CI? Pretty sure it will simplify the process it currently has right now

**Comment by yuyi98** [comment]
@nedpals  OK, I'll do it.

**Comment by nedpals** [comment]
Thanks 😃

**Comment by yuyi98** [comment]
@nedpals  Let's implement a simple and usable build.vsh, ci.yml will be updated after the later optimization.

**Comment by nedpals** [comment]
@yuyi98 sure! No problem for me 👍

**Pull request merged**
