### PR TITLE
analyzer: fix error of import analysis

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix error of import analysis.

image

### CODE REVIEW

**Review by nedpals — DISMISSED** [review]

**Review by nedpals — COMMENTED** [review]
The current workspace path (a.k.a `ls.root_uri`) is included in the list of import paths which should detect the folder: <https://github.com/vlang/vls/blob/use-tree-sitter/server/text_synchronization.v#L12>.

**Comment by yuyi98** [comment]
OK, I'll study it.

**Comment by yuyi98** [comment]
root_uri.path() return error path, it's not current file's project root path.

**Comment by yuyi98** [comment]
`root_uri` is root path at initialization, it's not the project root of the currently open document.

**Comment by nedpals** [comment]
@yuyi98 `ls.root_uri` is the project root. Based on your screenshot, `vls` is your project root and the directory of that currently opened file as well as the imported module is within the project root so it should be able to scan it.

**Comment by yuyi98** [comment]
I found during debugging that `ls.root_uri` is always' d:\Test\v\tt1 '

**Comment by nedpals** [comment]
> I found during debugging that `ls.root_uri` is always' d:\Test\v\tt1 ', It only assigns at initialization.

I see. I think missed something on your screenshot. You're opening a folder with multiple V projects right?

**Comment by nedpals** [comment]
@yuyi98 If that is the case, I suggest to transfer the `os.dir(ss.cur_dir)` inside the same location I linked earlier which is inside the `analyze` function.

**Comment by yuyi98** [comment]
OK, I'll try.

**Comment by yuyi98** [comment]
How to get the project root directory of the currently open file?
The current solution is `os.dir(os.dir(current_file_path)))`, that might not be right.

**Review by nedpals — APPROVED** [review]

**Pull request merged**
