### PR TITLE
fix(treesitter): always free token contents to prevent a memory leak

### PR DESCRIPTION
**Pull request by amaanq**
Detected with libfuzzer

Also just inlined the stack so there's no need to allocate twice for the stack and its data ptr

### CODE REVIEW

**Comment by medvednikov** [comment]
hey

thanks!

VLS is in the middle of a HUGE re-write, the repo is private atm, but it will be released in July:

https://github.com/v-analyzer

this re-write works great, vlang/vls is currently archived

**Comment by amaanq** [comment]
thanks for the response! Since this is archived, should I submit the changes to v-tree-sitter then? (Projects like nvim-treesitter use this to provide V syntax highlighting support, I can switch the repo to be v-tree-sitter if that's better)

**Comment by medvednikov** [comment]
I guess, yeah :)

**Comment by i582** [comment]
> thanks for the response! Since this is archived, should I submit the changes to v-tree-sitter then? (Projects like nvim-treesitter use this to provide V syntax highlighting support, I can switch the repo to be v-tree-sitter if that's better)

Hi
When we release a new version, it will be cool if your changes are pushed there, I will check if I have already fixed them in the current version, since I rewrote the scanner

**Comment by i582** [comment]
seems to be fixed in my version
Снимок экрана 2023-06-21 в 01 39 02

**Pull request closed without merging**
