### PR TITLE
Initial work on signature help support

### PR DESCRIPTION
**Pull request by streaksu**
To be followed by myself on subsequent pull requests, just I thought it would get big if I don't go little by little

### CODE REVIEW

**Comment by JalonSolov** [comment]
What type of signature?

**Comment by nedpals** [comment]
> What type of signature?

Signature help is a feature in LSP/VSCode that gives you the function (or any symbol) signature (e.g `fn foo(p1 string) int`) when the user presses a specific key (more commonly, `(` key)

**Comment by nedpals** [comment]
@streaksu Do you intent to merge this immediately or just mark it as draft?

**Comment by nedpals** [comment]
Okay, got it. Will merge it now

**Pull request merged**
