### PR TITLE
gitignore: add 'build' and 'build.exe'

### PR DESCRIPTION
**Pull request by yuyi98**
This PR add 'build' and 'build.exe' in gitignore.

- To simplify script execution, use `v build.vsh` to generated `build`, then we can use `build` directly.
- Add `build` and `build.exe` in gitignore.

### CODE REVIEW

**Comment by nedpals** [comment]
@medvednikov When compiling a VSH script, should they have the same behavior as a regular V program (keep the executable) or should they behave as if they are executed as `v run <file>.vsh`? I got the impression that `v build.vsh` will automatically remove the executable after execution

**Comment by nedpals** [comment]
To be honest, either `v run build.vsh` or `v build.vsh` should be fine but I'm more than satisfied if`v build.vsh` can execute and cleanup the executable automatically without adding them to the gitignore list. We'll keep this PR open in the meantime

**Comment by yuyi98** [comment]
OK, I see.

**Comment by JalonSolov** [comment]
Maybe V should always `run` .vsh files?  If you explicitly use the `.vsh` extension, then you shouldn't compile them to an executable and run them - they should always just be run.

**Comment by yuyi98** [comment]
OK, that's reasonable, I will close it.

**Pull request closed without merging**
