### PR TITLE
vls: fix unresolved import on install vscode-vlang

### LINKED ISSUE #72: Error building vls
RollerBushsqueaker

### PR DESCRIPTION
**Pull request by ken0x0a**
fix #72

Related: https://github.com/vlang/vscode-vlang/issues/211

### CODE REVIEW

**Comment by nedpals** [comment]
I don't think this is a good solution as it breaks for those users who install and use VLS on custom locations other than the .vmodules folder. Another thing is that this is more of an issue with the new imports mechanism of the V compiler rather VLS itself.

Would like to hear some opinions from @danieldaeschle about it.

**Comment by danieldaeschle** [comment]
This is not the correct fix imo.
We should fix it either in V or in the vscode extension.

**Comment by ken0x0a** [comment]
@danieldaeschle As I don't know vlang well yet, could you fix this issue?

**Comment by nedpals** [comment]
Will close this as the problem should be fixed on the compiler not on VLS

**Pull request closed without merging**
